// packages/webplayer-react/src/WebPlayerCustomMedia.tsx
import {
  type FC as ReactFC,
  type PropsWithChildren as ReactPropsWithChildren,
} from "react";

import { type WebPlayerCustomMediaProps } from "@car-cutter/core-ui";
import {
  ensureCustomElementsDefinition,
  webPlayerCustomMediaPropsToAttributes,
} from "@car-cutter/core-wc";

ensureCustomElementsDefinition();
const WebPlayerCustomMedia: ReactFC<
  ReactPropsWithChildren<WebPlayerCustomMediaProps>
> = ({ children, ...props }) => {
  const attributes = webPlayerCustomMediaPropsToAttributes(props);

  return (
    <cc-webplayer-custom-media {...attributes}>
      {children}
    </cc-webplayer-custom-media>
  );
};

export { WebPlayerCustomMedia, type WebPlayerCustomMediaProps };

// packages/webplayer-vue/src/WebPlayerCustomMedia.vue
<script lang="ts" setup>
import type { WebPlayerCustomMediaProps } from "@car-cutter/core";
import { webPlayerCustomMediaPropsToAttributes } from "@car-cutter/wc-webplayer";

export type { WebPlayerCustomMediaProps };

const props = defineProps<WebPlayerCustomMediaProps>();
const attributes = webPlayerCustomMediaPropsToAttributes(props);
</script>

<template>
  <cc-webplayer-custom-media v-bind="attributes">
    <slot></slot>
  </cc-webplayer-custom-media>
</template>
