// apps/demo-next/app/page.tsx
"use client"; // Mandatory only if we use events handlers

import { WebPlayer, WebPlayerCustomMedia } from "@car-cutter/next-webplayer";

export default function Home() {
  return (
    <main className="p-4 space-y-4">
      <h1 className="text-xl">Next App</h1>
      <WebPlayer
        className="mx-auto max-w-4xl"
        compositionUrl="https://cdn.car-cutter.com/libs/web-player/v3/demos/composition.json"
        infiniteCarrousel
        onCompositionLoaded={composition =>
          // eslint-disable-next-line no-console
          console.log("Composition loaded !", composition)
        }
      >
        <WebPlayerCustomMedia
          index={4}
          thumbnailSrc="https://cdn.car-cutter.com/libs/web-player/v3/assets/mocks/custom_thumbnail_audi.png"
        >
          <img src="https://cdn.car-cutter.com/libs/web-player/v3/assets/mocks/custom_image_1.jpg" />
        </WebPlayerCustomMedia>
      </WebPlayer>
    </main>
  );
}

// apps/demo-vue/src/App.vue
<script setup lang="ts">
import { WebPlayer, WebPlayerCustomMedia } from "@car-cutter/vue-webplayer";
</script>

<template>
  <div>
    <h1>Vue App</h1>
    <div class="webplayer-wrapper">
      <WebPlayer
        compositionUrl="https://cdn.car-cutter.com/libs/web-player/v3/demos/composition.json"
        :hideCategories="true"
        @compositionLoaded="
          composition => console.log('Composition loaded', composition)
        "
      >
        <WebPlayerCustomMedia
          :index="4"
          thumbnailSrc="https://cdn.car-cutter.com/libs/web-player/v3/assets/mocks/custom_thumbnail_audi.png"
        >
          <img
            src="https://cdn.car-cutter.com/libs/web-player/v3/assets/mocks/custom_image_1.jpg"
          />
        </WebPlayerCustomMedia>
      </WebPlayer>
    </div>
  </div>
</template>

<style scoped>
.webplayer-wrapper {
  max-width: 800px;
  margin-inline: auto;
}
</style>
