// packages/webplayer-vue/src/vue2/WebPlayerCustomMedia.vue
<script lang="ts">
import { defineComponent } from "vue";
import { WebPlayerCustomMediaProps } from "@car-cutter/core";
import { webPlayerCustomMediaPropsToAttributes } from "@car-cutter/wc-webplayer";

export type { WebPlayerCustomMediaProps };

export default defineComponent({
  props: {
    index: { type: Number, required: true },
    thumbnailSrc: String,
  },
  computed: {
    attributes() {
      return webPlayerCustomMediaPropsToAttributes(this.$props);
    },
  },
});
</script>

<template>
  <cc-webplayer-custom-media v-bind="attributes">
    <slot></slot>
  </cc-webplayer-custom-media>
</template>

// packages/webplayer-react/src/components/WebPlayerCustomMedia.tsx
import {
  type FC as ReactFC,
  type PropsWithChildren as ReactPropsWithChildren,
} from "react";

import type { WebPlayerCustomMediaProps } from "@car-cutter/core";
import { webPlayerCustomMediaPropsToAttributes } from "@car-cutter/core-wc";

const WebPlayerCustomMedia: ReactFC<
  ReactPropsWithChildren<WebPlayerCustomMediaProps>
> = ({ children, ...props }) => {
  const attributes = webPlayerCustomMediaPropsToAttributes(props);

  return (
    <cc-webplayer-custom-media {...attributes}>
      {children}
    </cc-webplayer-custom-media>
  );
};

export { WebPlayerCustomMedia, type WebPlayerCustomMediaProps };
