// packages/webplayer-vue/src/WebPlayer.vue
<script lang="ts" setup>
import type { WebPlayerProps } from "@car-cutter/core";
import { ensureCustomElementsDefinition } from "@car-cutter/wc-webplayer";

ensureCustomElementsDefinition();

defineProps<WebPlayerProps>();
</script>

<template>
  <cc-webplayer
    :composition-url="compositionUrl"
    :reverse360="reverse360"
    :min-image-width="minImageWidth"
    :max-image-width="maxImageWidth"
    :image-load-strategy="imageLoadStrategy"
    :flatten="flatten"
    :infinite-carrousel="infiniteCarrousel"
    :event-id="eventId"
    :allow-full-screen="allowFullScreen"
    :permanent-gallery="permanentGallery"
  >
  </cc-webplayer>
</template>

// packages/webplayer-next/src/WebPlayer.tsx
"use client";

import { useEffect } from "react";

import type { WebPlayerProps } from "@car-cutter/core-wc";

const WebPlayer: React.FC<WebPlayerProps> = ({
  compositionUrl,
  flatten,
  infiniteCarrousel,
  permanentGallery,
  imageLoadStrategy,
  minImageWidth,
  maxImageWidth,
  allowFullScreen,
  eventId,
  reverse360,
}) => {
  useEffect(() => {
    (async () => {
      const { ensureCustomElementsDefinition } = await import(
        "@car-cutter/core-wc"
      );
      ensureCustomElementsDefinition();
    })();
  }, []);

  return (
    // @ts-expect-error: [TODO] Should define into JSX.IntrinsicElements
    <cc-webplayer
      composition-url={compositionUrl}
      flatten={flatten}
      infinite-carrousel={infiniteCarrousel}
      permanent-gallery={permanentGallery}
      image-load-strategy={imageLoadStrategy}
      min-image-width={minImageWidth}
      max-image-width={maxImageWidth}
      allow-full-screen={allowFullScreen}
      event-id={eventId}
      reverse360={reverse360}
    />
  );
};

export default WebPlayer;
